# Generated by Django 3.0.5 on 2020-11-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrapingArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('Keywords', models.TextField()),
            ],
        ),
    ]
