# Generated by Django 3.0.5 on 2020-11-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapingArticles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapingarticles',
            old_name='Keywords',
            new_name='keywords',
        ),
    ]
